export default {
    name:'partner',
    title:'Partner',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string',
         },
        {
           name:'imgUrl',
           title:'imgUrl',
           type:'image',
           options:{
               hotspot:true
           } 
        }
    ]
}