export { default as Benefit} from './Benefit/Benefit'
export { default as Testimonial} from './Testimonial/Testimonial'
export { default as Header} from './Header/Header'
export { default as Footer} from './Footer/Footer'
export { default as Pricing} from './Pricing/Pricing'
export { default as Partner} from './Partner/Partner'